#!/usr/bin/env bun
/*
 * Generate omarchy/spalvos-{light,dark}/neovim.lua from ../nvim/lua/spalvos.lua.
 *
 * Omarchy copies a theme directory into ~/.config/omarchy/current/theme/ and
 * nothing in there may `require` a plugin, so each theme needs a SELF-CONTAINED
 * neovim.lua. Rather than maintain a second hand-written copy of the highlight
 * map (which is exactly how the two drifted apart from the Zed theme before),
 * wrap the port's source verbatim in an immediately-invoked function and append
 * the LazyVim spec. Zero duplicated colour logic — the generated file literally
 * contains the port.
 *
 * Run: `bun omarchy/generate-neovim.mjs` (from the repo root or anywhere).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const port = readFileSync(join(here, "../nvim/lua/spalvos.lua"), "utf8");

// The port is a module: `local M = {} ... return M`. Wrapping it in an IIFE
// turns it into an expression without touching a character of its body.
const indented = port.replace(/^(?=.)/gm, "  ");

for (const variant of ["light", "dark"]) {
  const Variant = variant[0].toUpperCase() + variant.slice(1);
  const out = `-- Spalvos ${Variant} for Neovim / LazyVim.
--
-- GENERATED by ../generate-neovim.mjs from ../../nvim/lua/spalvos.lua.
-- Do not edit: change the port and regenerate, or the two drift apart.
--
-- Self-contained by necessity — Omarchy copies this directory into
-- ~/.config/omarchy/current/theme/, where no plugin is available to require.
-- The port's source is inlined verbatim below; only the LazyVim spec at the
-- foot is added.
--
-- Transparency: set \`vim.g.spalvos_transparent = true\` (and optionally
-- \`vim.g.spalvos_float_transparent\`) in your own config. Do NOT strip
-- backgrounds in a plugin/after pass — that flattens floats and popups onto
-- the terminal background and the theme loses its surface hierarchy.

local M = (function()
${indented}
end)()

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = function()
        M.load("${variant}")
      end,
    },
  },
}
`;
  const path = join(here, `spalvos-${variant}`, "neovim.lua");
  writeFileSync(path, out);
  console.log(`wrote ${path} (${out.split("\n").length} lines)`);
}
